AWSTemplateFormatVersion: '2010-09-09'
Description: Responsive Serverless Test Stack
Transform: AWS::Serverless-2016-10-31

Parameters:
  StageName:
    Type: String
    Default: "test"
  MemorySize:
    Type: Number
    Default: 128

Resources:
  RegionalRestApi:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration: Regional
      StageName: !Ref StageName
      Cors:
        AllowCredentials: "'true'"
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"

  EdgeRestApi:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration: Edge
      StageName: !Ref StageName
      Cors:
        AllowCredentials: "'true'"
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"

  ApiUsagePlan:
    Type: 'AWS::ApiGateway::UsagePlan'
    DependsOn: 
      - RegionalRestApiStage
      - EdgeRestApiStage
    Properties:
      ApiStages:
        - ApiId: !Ref RegionalRestApi
          Stage: !Ref StageName
        - ApiId: !Ref EdgeRestApi
          Stage: !Ref StageName
      Quota:
        Limit: 10000
        Period: DAY
      Throttle:
        BurstLimit: 2000
        RateLimit: 1000
      UsagePlanName: !Sub "${StageName}Plan"

  ApiKey:
    Type: 'AWS::ApiGateway::ApiKey'
    DependsOn: 
      - RegionalRestApiStage
      - EdgeRestApiStage
    Properties:
      Enabled: true
      StageKeys:
        - RestApiId: !Ref RegionalRestApi
          StageName: !Ref StageName
        - RestApiId: !Ref EdgeRestApi
          StageName: !Ref StageName

  UsagePlanKey:
    Type: 'AWS::ApiGateway::UsagePlanKey'
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan

  SyncTestFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda.handler
      Runtime: nodejs12.x
      CodeUri: sync-test-function
      MemorySize: !Ref MemorySize
      AutoPublishAlias: live
      #ProvisionedConcurrencyConfig:
      #  ProvisionedConcurrentExecutions: 20
      Events:
        RegionalApiGet:
          Type: Api
          Properties:
            Method: get
            Path: /regional
            RestApiId: !Ref RegionalRestApi
        EdgeApiGet:
          Type: Api
          Properties:
            Method: get
            Path: /edge
            RestApiId: !Ref EdgeRestApi
        RegionalApiKeyGet:
          Type: Api
          Properties:
            Method: get
            Path: /regional-key
            RestApiId: !Ref RegionalRestApi
            Auth:
              ApiKeyRequired: true

  IdentityPool:
    Type: "AWS::Cognito::IdentityPool"
    Properties:
      AllowUnauthenticatedIdentities: true

  CognitoUnAuthorizedRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: 
              Federated: "cognito-identity.amazonaws.com"
            Action: 
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals: 
                "cognito-identity.amazonaws.com:aud": !Ref IdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": unauthenticated
      Policies:
        - PolicyName: "CognitoUnauthorizedPolicy"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action:
                  - "cognito-sync:*"
                Resource: "*"
              - Effect: "Allow"
                Action: "lambda:InvokeFunction"
                Resource:
                  - !Ref SyncTestFunction.Alias

  IdentityPoolRoleMapping:
    Type: "AWS::Cognito::IdentityPoolRoleAttachment"
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt CognitoUnAuthorizedRole.Arn
        unauthenticated: !GetAtt CognitoUnAuthorizedRole.Arn

Outputs:
  RegionalApiUrl:
    Value: !Sub "https://${RegionalRestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/regional"
  RegionalKeyApiUrl:
    Value: !Sub "https://${RegionalRestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/regional-key"
  EdgeApiUrl:
    Value: !Sub "https://${EdgeRestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/edge"
  SyncTestFunction:
    # Value: !Ref SyncTestFunction
    Value: !Ref SyncTestFunction.Alias
  Region:
    Value: !Sub "${AWS::Region}"
  IdentityPool:
    Value: !Ref IdentityPool
  ApiKeyId:
    Value: !Ref ApiKey
